package com.example.notesapp.ui.theme

import androidx.compose.ui.graphics.Color

//light colors
val primaryLight = Color(0xFF321E00)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF5D3C00)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF2E1F09)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF524027)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF172608)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF364826)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFF4E0002)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFF8C0009)
val onErrorContainerLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFFFF8F4)
val onBackgroundLight = Color(0xFF201B13)
val surfaceLight = Color(0xFFFFF8F4)
val onSurfaceLight = Color(0xFF000000)
val surfaceVariantLight = Color(0xFFF0E0CF)
val onSurfaceVariantLight = Color(0xFF2B2318)
val outlineLight = Color(0xFF4B4135)
val outlineVariantLight = Color(0xFF4B4135)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF362F27)
val inverseOnSurfaceLight = Color(0xFFFFFFFF)
val inversePrimaryLight = Color(0xFFFFE9CF)
val surfaceDimLight = Color(0xFFE4D8CC)
val surfaceBrightLight = Color(0xFFFFF8F4)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E5)
val surfaceContainerLight = Color(0xFFF9ECDF)
val surfaceContainerHighLight = Color(0xFFF3E6DA)
val surfaceContainerHighestLight = Color(0xFFEDE0D4)

// dark colors
val primaryDark = Color(0xFFFFFAF7)
val onPrimaryDark = Color(0xFF000000)
val primaryContainerDark = Color(0xFFF9C172)
val onPrimaryContainerDark = Color(0xFF000000)
val secondaryDark = Color(0xFFFFFAF7)
val onSecondaryDark = Color(0xFF000000)
val secondaryContainerDark = Color(0xFFE2C6A5)
val onSecondaryContainerDark = Color(0xFF000000)
val tertiaryDark = Color(0xFFF3FFE2)
val onTertiaryDark = Color(0xFF000000)
val tertiaryContainerDark = Color(0xFFBCD2A5)
val onTertiaryContainerDark = Color(0xFF000000)
val errorDark = Color(0xFFFFF9F9)
val onErrorDark = Color(0xFF000000)
val errorContainerDark = Color(0xFFFFBAB1)
val onErrorContainerDark = Color(0xFF000000)
val backgroundDark = Color(0xFF18120B)
val onBackgroundDark = Color(0xFFEDE0D4)
val surfaceDark = Color(0xFF18120B)
val onSurfaceDark = Color(0xFFFFFFFF)
val surfaceVariantDark = Color(0xFF4F4539)
val onSurfaceVariantDark = Color(0xFFFFFAF7)
val outlineDark = Color(0xFFD7C8B8)
val outlineVariantDark = Color(0xFFD7C8B8)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEDE0D4)
val inverseOnSurfaceDark = Color(0xFF000000)
val inversePrimaryDark = Color(0xFF3C2500)
val surfaceDimDark = Color(0xFF18120B)
val surfaceBrightDark = Color(0xFF3F3830)
val surfaceContainerLowestDark = Color(0xFF120D07)
val surfaceContainerLowDark = Color(0xFF201B13)
val surfaceContainerDark = Color(0xFF251F17)
val surfaceContainerHighDark = Color(0xFF2F2921)
val surfaceContainerHighestDark = Color(0xFF3B342B)